services:
  # Backend API service
  - type: web
    name: drone-ops-manager-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: DATABASE_URL
        fromDatabase:
          name: drone-ops-db
          property: connectionString

# Database
databases:
  - name: drone-ops-db
    databaseName: drone_ops_manager
    plan: free
    # Free PostgreSQL databases on Render are deleted after 90 days
    # For production, you should use the starter plan or higher
